<?php

function xmldb_teamevalquestion_comment_upgrade($oldversion) {
    global $DB;
    $dbman = $DB->get_manager();

    if ($oldversion < 2015121801) {
        // Code to add the column, generated by the 'View PHP Code' option of the XMLDB editor.

        upgrade_plugin_savepoint(true, 2015121801, 'teamevalquestion', 'comment');
    }

}

?>