<?php

function xmldb_local_teameval_upgrade($oldversion) {
    global $DB;
    $dbman = $DB->get_manager();

    /// Add a new column newcol to the mdl_myqtype_options
    if ($oldversion < 2015111800) {
        // Code to add the column, generated by the 'View PHP Code' option of the XMLDB editor.
        // Define field self to be added to teameval.
        $table = new xmldb_table('teameval');
        $field = new xmldb_field('self', XMLDB_TYPE_INTEGER, '2', null, XMLDB_NOTNULL, null, '1', 'public');

        // Conditionally launch add field self.
        if (!$dbman->field_exists($table, $field)) {
            $dbman->add_field($table, $field);
        }

        // Teameval savepoint reached.
        upgrade_plugin_savepoint(true, 2015111800, 'local', 'teameval');
    }

    if ($oldversion < 2015120200) {

        // Teameval savepoint reached.
        upgrade_plugin_savepoint(true, 2015120200, 'local', 'teameval');

    }


    return true;
}